### ISSUE TITLE
[BUG] Warning issued for Apple Silicon Device for Docker use case

### ISSUE THREAD

**Issue by karianna** [Markusgp/Untangle#106]
### Expected behavior
No warning to occur when running Docker use case on apple Silicon

### Actual behavior
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### Describe the bug cause
I image the base Docker image is an x86-64 one

### Steps to reproduce
Follow Docker section of README for Mac OS X users

### Screenshots
N/A

### Desktop (please complete the following information):
Mac OS X latest patched on Apple M2

**Comment by Karlo2001** [comment]
Hello @karianna,
Sorry for the delay. We are unfortunately not supporting Apple Silicon chips at this moment, as stated in our README file. We have had some issues with a docker image with the arm64 architecture and the CodeQL framework together. And because we do not own a device with an Apple Silicon chip, the testing of such an image is very limited and we are therefore not able to fix this issue at this moment.
Thanks for the support of the project
